blank_issues_enabled: false
contact_links:
  - name: Roadmap
    url: https://github.com/orgs/vidavidorra/projects/2
    about: View the roadmap for the vidavidorra organisation, as a GitHub Project.
