name: CI
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: ./.github/workflows/lint-commit-messages.yml
  lint:
    uses: ./.github/workflows/node-lint.yml
  release:
    uses: ./.github/workflows/release.yml
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
