name: Node.js test coverage
on:
  workflow_call:
    inputs:
      nodeVersion:
        type: string
        default: '24'
        required: false
      coverageFile:
        type: string
        default: './coverage/cobertura-coverage.xml'
        required: false
permissions:
  contents: read
  id-token: write
  pull-requests: write
jobs:
  run:
    name: Test coverage (Node.js ${{ inputs.nodeVersion }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Node.js ${{ inputs.nodeVersion }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Test
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ${{ inputs.coverageFile }}
          use_oidc: true
