name: Node.js lint
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
  workflow_call:
jobs:
  node-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Setup Node.js
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version: 16
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
