name: Node.js lint
on:
  workflow_call:
    inputs:
      nodeVersion:
        type: string
        default: '24'
        required: false
jobs:
  run:
    name: Lint (Node.js ${{ inputs.nodeVersion }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js ${{ inputs.nodeVersion }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
