name: Node.js lint
on:
  workflow_call:
    inputs:
      nodeVersion:
        type: string
        default: '18'
        required: false
jobs:
  run:
    name: Lint (Node.js ${{ inputs.nodeVersion }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node.js ${{ inputs.nodeVersion }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
