name: Node.js test coverage
on:
  workflow_call:
    inputs:
      nodeVersion:
        type: string
        default: '24'
        required: false
      coverageFile:
        type: string
        default: './coverage/cobertura-coverage.xml'
        required: false
permissions:
  contents: read
  id-token: write
  pull-requests: write
jobs:
  run:
    name: Test coverage (Node.js ${{ inputs.nodeVersion }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js ${{ inputs.nodeVersion }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Test
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          files: ${{ inputs.coverageFile }}
          use_oidc: true
