name: Node.js lint
on:
  workflow_call:
    inputs:
      nodeVersion:
        type: string
        default: '20'
        required: false
jobs:
  run:
    name: Lint (Node.js ${{ inputs.nodeVersion }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js ${{ inputs.nodeVersion }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
