name: Triage issue
on:
  workflow_call:
    inputs:
      projectUrl:
        type: string
        default: https://github.com/orgs/vidavidorra/projects/2
        required: false
    secrets:
      TRIAGE_APP_ID:
        description: 'GitHub App ID used for triage'
        required: true
      TRIAGE_PRIVATE_KEY:
        description: 'private key of the GitHub App used for triage'
        required: true
jobs:
  triage-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate token
        id: generate_token
        uses: vidavidorra/github-app-token@3bfc462f0355ce6268121fdb6c140a8bb4c6839a # v1.0.1
        with:
          appId: ${{ secrets.TRIAGE_APP_ID }}
          privateKey: ${{ secrets.TRIAGE_PRIVATE_KEY }}
      - uses: actions/add-to-project@0609a2702eefb44781da00f8e04901d6e5cd2b92 # v0.6.0
        with:
          project-url: ${{ inputs.projectUrl }}
          github-token: ${{ steps.generate_token.outputs.token }}
